### ISSUE TITLE
Installation is heavy because of the compilation of `mypy` from source

### ISSUE THREAD

**Issue by PaulGrandperrin** [thiagokokada/nix-alien#18]
I don't know very well how python works and how it's dependencies are integrated with nix but it looks like `mypy` is not really needed for the end user.

But `nix-alien` always wants `mypy` at version `0.942` which isn't in the cache, which makes every updates quite heavy.
On my machines, it monopolize my CPU for about 10 to 20 minutes.

If that's not really needed, would it be possible to avoid this?

**Comment by thiagokokada** [comment]
> I don't know very well how python works and how it's dependencies are integrated with nix but it looks like `mypy` is not really needed for the end user.
> 
> But `nix-alien` always wants `mypy` at version `0.942` which isn't in the cache, which makes every updates quite heavy. On my machines, it monopolize my CPU for about 10 to 20 minutes.
> 
> If that's not really needed, would it be possible to avoid this?

Yeah, it shouldn't be necessary for release. `mypy` and `black` are both declared as [dev dependencies only](https://github.com/thiagokokada/nix-alien/issues/18#issue-1220365599), so they shouldn't be needed in release binaries.

The issue is, I am using `poetry2nix` and AFAIR there isn't anyway to create a release-only derivation that don't try to build the dev dependencies. I will take a look anyway.

The alternative is that I may remove black/mypy from the `pyproject.toml` file and them just include somewhere else (`devShell` maybe), and run this as a separate step in the CI. This was reproducibility issues though.

**Comment by thiagokokada** [comment]
Should have been solved with PR #19.

Feel free to reopen this issue if this is not the case.
