### ISSUE TITLE
lib with spaces

### ISSUE THREAD

**Issue by hissssst** [thiagokokada/nix-alien#31]
`ldd myprogram` shows something like `lib.so => /path/to/Directory With Spaces/lib.so (0xdeadbeef)`
And `nix-alien` fails to parse this

**Comment by thiagokokada** [comment]
This looks like a bug in https://github.com/Parquery/pylddwrap instead.

**Comment by hissssst** [comment]
Yes, it is. Could you please open in issue there?

**Comment by thiagokokada** [comment]
> Yes, it is. Could you please open in issue there?

Could you open an issue there instead? Probably have more context.

**Comment by hissssst** [comment]
No, I am a user of `nix-alien`.
And you're a user of this library.

I've provided everything I knew.
Good luck

**Comment by thiagokokada** [comment]
> I mean, when I discover bug with video in my browser and it turns out that there is a problem with VA-API, Firefox team doesn't send me there to fill a bug for them. This makes no sense

The difference is that Firefox developers are paid to fix issues. I am not.

I have zero context of your bug specially because it lacks a stack trace or error, this is why I asked you to open it instead.

Anyway, thanks for opening an issue in the proper repository. Could have done without the passive-aggressive comment though.

**Comment by hissssst** [comment]
> The difference is that Firefox developers are paid to fix issues. I am not.

I am not paid for opening issues too. So payment is not the point here. The problem here is purely technical: I just came across an issue and it could be unrelated to the dependency you were using. Or it could be related to the `pylddwrap` but it could be just a misuse of the options or an already fixed bug, which could be fixed with dependency version bump.

So the problem here is very clear. I am a user of your software. And you are a user of `pylddwrap`. And users fill the bug for their developers. This is not transitive. Because I don't know how `nix-alien` uses `pylddwrap`, and you do.

And sorry for being passive aggressive, I didn't mean to behave like that. It is hard to keep patience when you're fleeing from war in your homeland.

**Comment by hissssst** [comment]
Here's a stacktrace

```
$ nix-alien ./CoQ
Traceback (most recent call last):
  File "/nix/store/kf85p6ym80ii9nkwapv1zfabyvzpi9rl-python3.9-nix-alien-0.1.0/bin/.nix-alien-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/kf85p6ym80ii9nkwapv1zfabyvzpi9rl-python3.9-nix-alien-0.1.0/lib/python3.9/site-packages/nix_alien/fhs_env.py", line 224, in main
    create_fhs_env(
  File "/nix/store/kf85p6ym80ii9nkwapv1zfabyvzpi9rl-python3.9-nix-alien-0.1.0/lib/python3.9/site-packages/nix_alien/fhs_env.py", line 54, in create_fhs_env
    fhs_shell = create_fhs_env_drv(
  File "/nix/store/kf85p6ym80ii9nkwapv1zfabyvzpi9rl-python3.9-nix-alien-0.1.0/lib/python3.9/site-packages/nix_alien/fhs_env.py", line 27, in create_fhs_env_drv
    packages = find_libs(path, silent, additional_libs)
  File "/nix/store/kf85p6ym80ii9nkwapv1zfabyvzpi9rl-python3.9-nix-alien-0.1.0/lib/python3.9/site-packages/nix_alien/libs.py", line 37, in find_libs
    deps = list_dependencies(path=path)
  File "/nix/store/yb4wv6mjsrfci6ycq3r960lyywyz79qq-python3.9-icontract-2.6.1/lib/python3.9/site-packages/icontract/_checkers.py", line 641, in wrapper
    result = func(*args, **kwargs)
  File "/nix/store/ikpqp76vmlwryqxr4l2mxhn1l77ir3r7-python3.9-pylddwrap-1.2.1/lib/python3.9/site-packages/lddwrap/__init__.py", line 224, in list_dependencies
    dependencies = _cmd_output_parser(cmd_out=out)  # type: List[Dependency]
  File "/nix/store/ikpqp76vmlwryqxr4l2mxhn1l77ir3r7-python3.9-pylddwrap-1.2.1/lib/python3.9/site-packages/lddwrap/__init__.py", line 273, in _cmd_output_parser
    dep = _parse_line(line=line)
  File "/nix/store/ikpqp76vmlwryqxr4l2mxhn1l77ir3r7-python3.9-pylddwrap-1.2.1/lib/python3.9/site-packages/lddwrap/__init__.py", line 142, in _parse_line
    raise RuntimeError(
RuntimeError: Expected 4 parts in the line but found 6: UnityPlayer.so => /home/user/games/q u d/./UnityPlayer.so (0x00007fa7b9534000)
```

**Comment by thiagokokada** [comment]
> I am not paid for opening issues too. So payment is not the point here.

Of course it is. If I was paid for doing something I would have some responsibility about those issues. Since I am not I have zero motivation to work on them.

> So the problem here is very clear. I am a user of your software. And you are a user of `pylddwrap`. And users fill the bug for their developers. This is not transitive. Because I don't know how `nix-alien` uses `pylddwrap`, while you do.

No, sorry, you are wrong because you're assuming that all software are written with users in mind: it is not. This software is mostly written for me for my use cases. I really don't care too much if the software is not working right for your specific use case, since it works fine for me.

I still try as much as I can to help, but I generally expect folks to be respectful. Instead of being passive-aggressive or trying to argue why this whole issue is my responsibility, you could just say that you didn't had enough time or knowledge, and I would probably do this when I had enough time. But well, thanks for your behavior I have zero motivation to work in this particular issue.

> And sorry for being passive aggressive, I didn't mean to behave like that. It is hard to keep patience when you're fleeing from war in your homeland.

You know, I can't have a crystal ball to see your circumstances. Using it as a excuse just looks to me that you would have this behavior anyway even if it wasn't the case.

**Comment by thiagokokada** [comment]
Locking this since the issue was opened in upstream.

**Comment by thiagokokada** [comment]
PR opened upstream to fix the issue: https://github.com/Parquery/pylddwrap/pull/26

**Comment by thiagokokada** [comment]
Fixed by commit https://github.com/thiagokokada/nix-alien/pull/40.

If this is still a problem please open another issue, but please without the passive-aggressive tone from this one.
