### ISSUE TITLE
poetry2nix needs an update to work with nixpkgs/master

### ISSUE THREAD

**Issue by pshirshov** [thiagokokada/nix-alien#45]
See https://github.com/NixOS/nixpkgs/issues/198137#issuecomment-1299281705

**Comment by lilyinstarlight** [comment]
Something else also needs to be done with these lines before it will work with latest nixpkgs-unstable, since it overrides the python package set with non-module derivations (which is no longer allowed): https://github.com/thiagokokada/nix-alien/blob/b47b2d88b2d0d825efd309f7fd58c76df34f7048/nix-alien.nix#L19-L21

**Comment by thiagokokada** [comment]
Ugh, poetry2nix strikes again. I am seriously simple considering remove Poetry and poetry2nix from this project and using simple `buildPythonApplication` instead.

**Comment by thiagokokada** [comment]
Commit bdb31bb8f312ccc62f8c6708dfbea0dbf3e65755 should fix this issue. If this is not the case please reopen the issue.
